service:
  name: portfolio-todo-app

plugins:
  - serverless-webpack
  - serverless-aws-documentation
custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Todo List Serverless API

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true


provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}

  tracing:
    lambda: true
    apiGateway: true

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    TODO_TABLE: Todo-${self:provider.stage}
    INDEX_USER_ID: IndexUserId

resources:
  Resources:
    TodoTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: todoId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: indexKey
            AttributeType: S
        KeySchema:
          - AttributeName: todoId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TODO_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_USER_ID}
            KeySchema:
            - AttributeName: todoId
              KeyType: HASH
            - AttributeName: indexKey
              KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
